# Generated by Django 3.2.7 on 2022-05-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220517_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_card',
            old_name='images',
            new_name='profil',
        ),
    ]
